# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: janus/v1/identity.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'janus/v1/identity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from janus.v1 import common_pb2 as janus_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17janus/v1/identity.proto\x12\x08janus.v1\x1a\x15janus/v1/common.proto\"\xc5\x03\n\x12IdentityTrustEvent\x12\x35\n\x04kind\x18\x01 \x01(\x0e\x32!.janus.v1.IdentityTrustEvent.KindR\x04kind\x12\x16\n\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x15\n\x06key_id\x18\x03 \x01(\tR\x05keyId\x12\x1d\n\npublic_key\x18\x04 \x01(\x0cR\tpublicKey\x12\x1c\n\talgorithm\x18\x05 \x01(\tR\talgorithm\x12#\n\rcredential_id\x18\x06 \x01(\tR\x0c\x63redentialId\x12\x18\n\x07subject\x18\x07 \x01(\tR\x07subject\x12\x1f\n\x02\x62y\x18\x08 \x01(\x0b\x32\x0f.janus.v1.ActorR\x02\x62y\x12\x16\n\x06reason\x18\t \x01(\tR\x06reason\"\x93\x01\n\x04Kind\x12\x14\n\x10KIND_UNSPECIFIED\x10\x00\x12\x1b\n\x17KIND_ISSUER_KEY_TRUSTED\x10\x01\x12\x1b\n\x17KIND_ISSUER_KEY_REVOKED\x10\x02\x12\x1e\n\x1aKIND_CREDENTIAL_REGISTERED\x10\x03\x12\x1b\n\x17KIND_CREDENTIAL_REVOKED\x10\x04\x42\x37Z5github.com/mustafarslan/janus/gen/go/janus/v1;janusv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'janus.v1.identity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/mustafarslan/janus/gen/go/janus/v1;janusv1'
  _globals['_IDENTITYTRUSTEVENT']._serialized_start=61
  _globals['_IDENTITYTRUSTEVENT']._serialized_end=514
  _globals['_IDENTITYTRUSTEVENT_KIND']._serialized_start=367
  _globals['_IDENTITYTRUSTEVENT_KIND']._serialized_end=514
# @@protoc_insertion_point(module_scope)
