# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from janus.v1 import orchd_pb2 as janus_dot_v1_dot_orchd__pb2


class OrchestratorServiceStub(object):
    """The service boundary.

    One process owns an evidence directory, so everything that needs to
    append to one — an SDK starting a saga, an MCP proxy turning a tool call into
    a step, a console recording an approval — has to ask that process rather than
    open the log itself. This file is what they ask.

    The request and response types are wrappers. The payloads inside them are the
    JTP messages already used as evidence-log records: a SagaBegin sent here is
    byte-for-byte the SagaBegin that lands in the log. That is the point —
    one grammar for wire and record — and it is why there is no separate "API
    model" here to drift from the evidence.

    What this service does NOT offer is a shortcut. Every effectful operation
    still goes through gate admission, the registry, the outbox and the log in
    the same order a single-process coordinator would take. A service is a
    tempting place to put a fast path; there is not one, and an RPC that skipped
    a gate would be indistinguishable in the log from an attack.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BeginSaga = channel.unary_unary(
                '/janus.v1.OrchestratorService/BeginSaga',
                request_serializer=janus_dot_v1_dot_orchd__pb2.BeginSagaRequest.SerializeToString,
                response_deserializer=janus_dot_v1_dot_orchd__pb2.BeginSagaResponse.FromString,
                _registered_method=True)
        self.PrepareStep = channel.unary_unary(
                '/janus.v1.OrchestratorService/PrepareStep',
                request_serializer=janus_dot_v1_dot_orchd__pb2.PrepareStepRequest.SerializeToString,
                response_deserializer=janus_dot_v1_dot_orchd__pb2.PrepareStepResponse.FromString,
                _registered_method=True)
        self.CompleteStep = channel.unary_unary(
                '/janus.v1.OrchestratorService/CompleteStep',
                request_serializer=janus_dot_v1_dot_orchd__pb2.CompleteStepRequest.SerializeToString,
                response_deserializer=janus_dot_v1_dot_orchd__pb2.CompleteStepResponse.FromString,
                _registered_method=True)
        self.RecordAnswer = channel.unary_unary(
                '/janus.v1.OrchestratorService/RecordAnswer',
                request_serializer=janus_dot_v1_dot_orchd__pb2.RecordAnswerRequest.SerializeToString,
                response_deserializer=janus_dot_v1_dot_orchd__pb2.RecordAnswerResponse.FromString,
                _registered_method=True)
        self.RegisterCredential = channel.unary_unary(
                '/janus.v1.OrchestratorService/RegisterCredential',
                request_serializer=janus_dot_v1_dot_orchd__pb2.RegisterCredentialRequest.SerializeToString,
                response_deserializer=janus_dot_v1_dot_orchd__pb2.RegisterCredentialResponse.FromString,
                _registered_method=True)
        self.RevokeCredential = channel.unary_unary(
                '/janus.v1.OrchestratorService/RevokeCredential',
                request_serializer=janus_dot_v1_dot_orchd__pb2.RevokeCredentialRequest.SerializeToString,
                response_deserializer=janus_dot_v1_dot_orchd__pb2.RevokeCredentialResponse.FromString,
                _registered_method=True)
        self.RevokeIssuerKey = channel.unary_unary(
                '/janus.v1.OrchestratorService/RevokeIssuerKey',
                request_serializer=janus_dot_v1_dot_orchd__pb2.RevokeIssuerKeyRequest.SerializeToString,
                response_deserializer=janus_dot_v1_dot_orchd__pb2.RevokeIssuerKeyResponse.FromString,
                _registered_method=True)
        self.ReplicationHead = channel.unary_unary(
                '/janus.v1.OrchestratorService/ReplicationHead',
                request_serializer=janus_dot_v1_dot_orchd__pb2.ReplicationHeadRequest.SerializeToString,
                response_deserializer=janus_dot_v1_dot_orchd__pb2.ReplicationHeadResponse.FromString,
                _registered_method=True)
        self.ReplicationSegments = channel.unary_unary(
                '/janus.v1.OrchestratorService/ReplicationSegments',
                request_serializer=janus_dot_v1_dot_orchd__pb2.ReplicationSegmentsRequest.SerializeToString,
                response_deserializer=janus_dot_v1_dot_orchd__pb2.ReplicationSegmentsResponse.FromString,
                _registered_method=True)
        self.ReplicationRead = channel.unary_unary(
                '/janus.v1.OrchestratorService/ReplicationRead',
                request_serializer=janus_dot_v1_dot_orchd__pb2.ReplicationReadRequest.SerializeToString,
                response_deserializer=janus_dot_v1_dot_orchd__pb2.ReplicationReadResponse.FromString,
                _registered_method=True)
        self.HoldEffect = channel.unary_unary(
                '/janus.v1.OrchestratorService/HoldEffect',
                request_serializer=janus_dot_v1_dot_orchd__pb2.HoldEffectRequest.SerializeToString,
                response_deserializer=janus_dot_v1_dot_orchd__pb2.HoldEffectResponse.FromString,
                _registered_method=True)
        self.ReleaseEffects = channel.unary_unary(
                '/janus.v1.OrchestratorService/ReleaseEffects',
                request_serializer=janus_dot_v1_dot_orchd__pb2.ReleaseEffectsRequest.SerializeToString,
                response_deserializer=janus_dot_v1_dot_orchd__pb2.ReleaseEffectsResponse.FromString,
                _registered_method=True)
        self.ResolveParticipant = channel.unary_unary(
                '/janus.v1.OrchestratorService/ResolveParticipant',
                request_serializer=janus_dot_v1_dot_orchd__pb2.ResolveParticipantRequest.SerializeToString,
                response_deserializer=janus_dot_v1_dot_orchd__pb2.ResolveParticipantResponse.FromString,
                _registered_method=True)
        self.GetSaga = channel.unary_unary(
                '/janus.v1.OrchestratorService/GetSaga',
                request_serializer=janus_dot_v1_dot_orchd__pb2.GetSagaRequest.SerializeToString,
                response_deserializer=janus_dot_v1_dot_orchd__pb2.GetSagaResponse.FromString,
                _registered_method=True)
        self.DeliverEffects = channel.stream_stream(
                '/janus.v1.OrchestratorService/DeliverEffects',
                request_serializer=janus_dot_v1_dot_orchd__pb2.DeliverEffectsRequest.SerializeToString,
                response_deserializer=janus_dot_v1_dot_orchd__pb2.DeliverEffectsResponse.FromString,
                _registered_method=True)
        self.WatchSagas = channel.unary_stream(
                '/janus.v1.OrchestratorService/WatchSagas',
                request_serializer=janus_dot_v1_dot_orchd__pb2.WatchSagasRequest.SerializeToString,
                response_deserializer=janus_dot_v1_dot_orchd__pb2.WatchSagasResponse.FromString,
                _registered_method=True)


class OrchestratorServiceServicer(object):
    """The service boundary.

    One process owns an evidence directory, so everything that needs to
    append to one — an SDK starting a saga, an MCP proxy turning a tool call into
    a step, a console recording an approval — has to ask that process rather than
    open the log itself. This file is what they ask.

    The request and response types are wrappers. The payloads inside them are the
    JTP messages already used as evidence-log records: a SagaBegin sent here is
    byte-for-byte the SagaBegin that lands in the log. That is the point —
    one grammar for wire and record — and it is why there is no separate "API
    model" here to drift from the evidence.

    What this service does NOT offer is a shortcut. Every effectful operation
    still goes through gate admission, the registry, the outbox and the log in
    the same order a single-process coordinator would take. A service is a
    tempting place to put a fast path; there is not one, and an RPC that skipped
    a gate would be indistinguishable in the log from an attack.
    """

    def BeginSaga(self, request, context):
        """BeginSaga admits a plan and records it. Admission is against the gate
        policy AND the registry: a step whose declared effect class differs from
        its registered manifest is refused here rather than at the effect.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareStep(self, request, context):
        """PrepareStep advances the saga and hands the caller the step it is expected
        to run. It is a request, not an instruction: the coordinator decides
        whether the step may be prepared, and a step whose pre-execution gate has
        not passed comes back refused with the reason.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteStep(self, request, context):
        """CompleteStep reports what a participant did. The response is sent only
        after the result is durable — an acknowledgement before the append would
        be the service claiming evidence that does not exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordAnswer(self, request, context):
        """RecordAnswer records a validator's or a human's answer to a gate. This is
        why a console no longer has to wait for a coordinator to let go of the
        log.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterCredential(self, request, context):
        """RegisterCredential enrols a WebAuthn authenticator for a person, so that a
        gate requiring a step-up has something to verify against.

        Deliberately narrower than "record an identity trust event". Trusting an
        OIDC issuer key is not offered here and never should be: a caller that
        could add a trusted issuer could mint tokens establishing any role it
        liked, which is a larger authority than anything else in this service
        grants. Issuer trust is an operator action, out of band.

        Registering a credential is bounded by comparison. A credential alone
        establishes nothing — verification requires the credential's subject to
        match the subject of a verified ID token — so a rogue registration is
        useless without a token for that person, which this service cannot produce.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeCredential(self, request, context):
        """RevokeCredential withdraws an authenticator that has been lost or stolen.

        It is here rather than on the console, and that placement is the whole
        decision. A page that can revoke a credential from a session is a page a
        stolen session can use to remove the control it is about to bypass, so the
        console offers no revoke button and never should. This is the operator
        plane: reaching it means reaching the daemon's address, which a browser
        session does not.

        Revocation is not the inverse of registration in one respect worth naming:
        an approval given before the revocation stays valid, because it was valid
        when it was given. `FoldTrustUntil` is what re-verification uses, and
        treating a later revocation as retroactive would rewrite history every time
        somebody lost a laptop.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeIssuerKey(self, request, context):
        """RevokeIssuerKey withdraws one signing key of one OIDC issuer.

        Trusting an issuer is NOT here and must not be. Whoever can add a trusted
        issuer can mint a token establishing any role, which is a larger authority
        than anything else this service grants, so it stays configuration read from
        the daemon's own command line where a session cannot reach it
        (janus-orchd -issuer-jwks).

        Revocation is the opposite direction and that asymmetry is the reason it is
        allowed through the wire: it removes authority rather than granting it, and
        a deployment that has just learned an issuer key is compromised should not
        have to schedule a restart to stop honouring it. The same reasoning put
        RevokeCredential here while registration stayed narrower.

        Not retroactive, for the reason RevokeCredential is not: an approval given
        before the revocation was valid when it was given, and `FoldTrustUntil` is
        what re-verification folds. Treating this as retroactive would invalidate
        every approval an issuer ever established each time it rotated a key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicationHead(self, request, context):
        """The replication surface: three read-only calls that let a follower mirror
        this daemon's evidence directory.

        Read-only, and deliberately so. A follower asks for bytes and is told what
        has been acknowledged; it cannot write, cannot promote anything, and cannot
        ask this daemon to stop being the writer. Promotion is an operator act on
        the *replica* (6i), not something a primary can be talked into.

        Three unary calls rather than one server-driven stream. The stream would be
        fewer round trips and is not built, because the round trips have not been
        measured — and because these three are exactly the interface the follower's
        rules were established against, so the transport carries a shape that is
        already tested rather than inventing a second one.

        ReplicationHead reports what this daemon has durably acknowledged.

        The chain hash is not decoration: a follower compares it against its own at
        the same sequence, so a primary that served a different log is caught rather
        than copied. A response stating a sequence with no chain is refused by the
        follower.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicationSegments(self, request, context):
        """ReplicationSegments lists this daemon's segment ids, ascending.

        Every file, including one created ahead of a rotation and not yet written
        to. Filtering here would be the primary deciding what the follower may see,
        and rule three — a cursor may only pass a *sealed* segment — is the
        follower's to enforce.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicationRead(self, request, context):
        """ReplicationRead returns a slice of one segment as this daemon currently has
        it, with that segment's current length.

        The length is what lets a follower notice its own copy is *longer* — which
        means this daemon crashed and recovery truncated a torn tail the follower
        had already copied.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HoldEffect(self, request, context):
        """HoldEffect withholds an effect until its saga commits.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseEffects(self, request, context):
        """ReleaseEffects delivers what a committed saga was holding. It is safe to
        call on a saga that has not committed: the outbox refuses, and the refusal
        is the invariant working rather than an error to route around.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveParticipant(self, request, context):
        """ResolveParticipant returns what a pinned manifest version declares.

        It exists for one job: letting a client check its own declarations against
        the registry before it starts a saga. An SDK that declares a step as PURE
        when the manifest says the action moves money should find out when it
        connects, not at admission and certainly not at a gate.

        It is not a discovery API. One pinned version in, its actions out — no
        listing, no search, no "what participants exist". That surface is not
        built and belongs with the AgentCard projection.

        **Nothing may gate on this response.** The daemon re-checks every plan
        against the registry at admission, from the log, and that check is the
        enforcement. This is a courtesy that fails fast; a caller that treated it
        as permission would be trusting a value it was handed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSaga(self, request, context):
        """GetSaga returns the projection. It is derived from the log on demand, so
        two callers asking at the same sequence get the same answer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeliverEffects(self, request_iterator, context):
        """DeliverEffects is how a process that can reach a target lends the outbox
        the ability to reach it.

        The stream runs the other way round from every other method here: the
        client opens it, declares which targets it serves, and then waits to be
        told what to deliver. That direction is deliberate. Invariant I1 requires
        EFFECT_RELEASING to be appended durably *before* the delivery is attempted,
        and only this process can append — so the decision to deliver, the ordering
        around it, the retry budget and the poisoning all stay here. A client that
        claimed effects and delivered them on its own initiative would have taken
        custody of the one ordering the whole outbox exists to guarantee.

        A disconnected deliverer is therefore not a silent hold: the target simply
        has no deliverer, which the outbox already refuses on, loudly, with the
        effect still held and still retryable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchSagas(self, request, context):
        """WatchSagas streams projections as they change.

        It exists so a client does not have to poll to notice that a gate was
        answered or a participant is wanted. It carries last_seq on every message
        for the same reason the Phase 6 projections will: a stream can drop, and a
        consumer that cannot say where it got to has to start again.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BeginSaga': grpc.unary_unary_rpc_method_handler(
                    servicer.BeginSaga,
                    request_deserializer=janus_dot_v1_dot_orchd__pb2.BeginSagaRequest.FromString,
                    response_serializer=janus_dot_v1_dot_orchd__pb2.BeginSagaResponse.SerializeToString,
            ),
            'PrepareStep': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareStep,
                    request_deserializer=janus_dot_v1_dot_orchd__pb2.PrepareStepRequest.FromString,
                    response_serializer=janus_dot_v1_dot_orchd__pb2.PrepareStepResponse.SerializeToString,
            ),
            'CompleteStep': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteStep,
                    request_deserializer=janus_dot_v1_dot_orchd__pb2.CompleteStepRequest.FromString,
                    response_serializer=janus_dot_v1_dot_orchd__pb2.CompleteStepResponse.SerializeToString,
            ),
            'RecordAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordAnswer,
                    request_deserializer=janus_dot_v1_dot_orchd__pb2.RecordAnswerRequest.FromString,
                    response_serializer=janus_dot_v1_dot_orchd__pb2.RecordAnswerResponse.SerializeToString,
            ),
            'RegisterCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCredential,
                    request_deserializer=janus_dot_v1_dot_orchd__pb2.RegisterCredentialRequest.FromString,
                    response_serializer=janus_dot_v1_dot_orchd__pb2.RegisterCredentialResponse.SerializeToString,
            ),
            'RevokeCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeCredential,
                    request_deserializer=janus_dot_v1_dot_orchd__pb2.RevokeCredentialRequest.FromString,
                    response_serializer=janus_dot_v1_dot_orchd__pb2.RevokeCredentialResponse.SerializeToString,
            ),
            'RevokeIssuerKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeIssuerKey,
                    request_deserializer=janus_dot_v1_dot_orchd__pb2.RevokeIssuerKeyRequest.FromString,
                    response_serializer=janus_dot_v1_dot_orchd__pb2.RevokeIssuerKeyResponse.SerializeToString,
            ),
            'ReplicationHead': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicationHead,
                    request_deserializer=janus_dot_v1_dot_orchd__pb2.ReplicationHeadRequest.FromString,
                    response_serializer=janus_dot_v1_dot_orchd__pb2.ReplicationHeadResponse.SerializeToString,
            ),
            'ReplicationSegments': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicationSegments,
                    request_deserializer=janus_dot_v1_dot_orchd__pb2.ReplicationSegmentsRequest.FromString,
                    response_serializer=janus_dot_v1_dot_orchd__pb2.ReplicationSegmentsResponse.SerializeToString,
            ),
            'ReplicationRead': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicationRead,
                    request_deserializer=janus_dot_v1_dot_orchd__pb2.ReplicationReadRequest.FromString,
                    response_serializer=janus_dot_v1_dot_orchd__pb2.ReplicationReadResponse.SerializeToString,
            ),
            'HoldEffect': grpc.unary_unary_rpc_method_handler(
                    servicer.HoldEffect,
                    request_deserializer=janus_dot_v1_dot_orchd__pb2.HoldEffectRequest.FromString,
                    response_serializer=janus_dot_v1_dot_orchd__pb2.HoldEffectResponse.SerializeToString,
            ),
            'ReleaseEffects': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseEffects,
                    request_deserializer=janus_dot_v1_dot_orchd__pb2.ReleaseEffectsRequest.FromString,
                    response_serializer=janus_dot_v1_dot_orchd__pb2.ReleaseEffectsResponse.SerializeToString,
            ),
            'ResolveParticipant': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveParticipant,
                    request_deserializer=janus_dot_v1_dot_orchd__pb2.ResolveParticipantRequest.FromString,
                    response_serializer=janus_dot_v1_dot_orchd__pb2.ResolveParticipantResponse.SerializeToString,
            ),
            'GetSaga': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSaga,
                    request_deserializer=janus_dot_v1_dot_orchd__pb2.GetSagaRequest.FromString,
                    response_serializer=janus_dot_v1_dot_orchd__pb2.GetSagaResponse.SerializeToString,
            ),
            'DeliverEffects': grpc.stream_stream_rpc_method_handler(
                    servicer.DeliverEffects,
                    request_deserializer=janus_dot_v1_dot_orchd__pb2.DeliverEffectsRequest.FromString,
                    response_serializer=janus_dot_v1_dot_orchd__pb2.DeliverEffectsResponse.SerializeToString,
            ),
            'WatchSagas': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchSagas,
                    request_deserializer=janus_dot_v1_dot_orchd__pb2.WatchSagasRequest.FromString,
                    response_serializer=janus_dot_v1_dot_orchd__pb2.WatchSagasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'janus.v1.OrchestratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('janus.v1.OrchestratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorService(object):
    """The service boundary.

    One process owns an evidence directory, so everything that needs to
    append to one — an SDK starting a saga, an MCP proxy turning a tool call into
    a step, a console recording an approval — has to ask that process rather than
    open the log itself. This file is what they ask.

    The request and response types are wrappers. The payloads inside them are the
    JTP messages already used as evidence-log records: a SagaBegin sent here is
    byte-for-byte the SagaBegin that lands in the log. That is the point —
    one grammar for wire and record — and it is why there is no separate "API
    model" here to drift from the evidence.

    What this service does NOT offer is a shortcut. Every effectful operation
    still goes through gate admission, the registry, the outbox and the log in
    the same order a single-process coordinator would take. A service is a
    tempting place to put a fast path; there is not one, and an RPC that skipped
    a gate would be indistinguishable in the log from an attack.
    """

    @staticmethod
    def BeginSaga(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus.v1.OrchestratorService/BeginSaga',
            janus_dot_v1_dot_orchd__pb2.BeginSagaRequest.SerializeToString,
            janus_dot_v1_dot_orchd__pb2.BeginSagaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus.v1.OrchestratorService/PrepareStep',
            janus_dot_v1_dot_orchd__pb2.PrepareStepRequest.SerializeToString,
            janus_dot_v1_dot_orchd__pb2.PrepareStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus.v1.OrchestratorService/CompleteStep',
            janus_dot_v1_dot_orchd__pb2.CompleteStepRequest.SerializeToString,
            janus_dot_v1_dot_orchd__pb2.CompleteStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus.v1.OrchestratorService/RecordAnswer',
            janus_dot_v1_dot_orchd__pb2.RecordAnswerRequest.SerializeToString,
            janus_dot_v1_dot_orchd__pb2.RecordAnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus.v1.OrchestratorService/RegisterCredential',
            janus_dot_v1_dot_orchd__pb2.RegisterCredentialRequest.SerializeToString,
            janus_dot_v1_dot_orchd__pb2.RegisterCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus.v1.OrchestratorService/RevokeCredential',
            janus_dot_v1_dot_orchd__pb2.RevokeCredentialRequest.SerializeToString,
            janus_dot_v1_dot_orchd__pb2.RevokeCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeIssuerKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus.v1.OrchestratorService/RevokeIssuerKey',
            janus_dot_v1_dot_orchd__pb2.RevokeIssuerKeyRequest.SerializeToString,
            janus_dot_v1_dot_orchd__pb2.RevokeIssuerKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicationHead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus.v1.OrchestratorService/ReplicationHead',
            janus_dot_v1_dot_orchd__pb2.ReplicationHeadRequest.SerializeToString,
            janus_dot_v1_dot_orchd__pb2.ReplicationHeadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicationSegments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus.v1.OrchestratorService/ReplicationSegments',
            janus_dot_v1_dot_orchd__pb2.ReplicationSegmentsRequest.SerializeToString,
            janus_dot_v1_dot_orchd__pb2.ReplicationSegmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicationRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus.v1.OrchestratorService/ReplicationRead',
            janus_dot_v1_dot_orchd__pb2.ReplicationReadRequest.SerializeToString,
            janus_dot_v1_dot_orchd__pb2.ReplicationReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HoldEffect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus.v1.OrchestratorService/HoldEffect',
            janus_dot_v1_dot_orchd__pb2.HoldEffectRequest.SerializeToString,
            janus_dot_v1_dot_orchd__pb2.HoldEffectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseEffects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus.v1.OrchestratorService/ReleaseEffects',
            janus_dot_v1_dot_orchd__pb2.ReleaseEffectsRequest.SerializeToString,
            janus_dot_v1_dot_orchd__pb2.ReleaseEffectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveParticipant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus.v1.OrchestratorService/ResolveParticipant',
            janus_dot_v1_dot_orchd__pb2.ResolveParticipantRequest.SerializeToString,
            janus_dot_v1_dot_orchd__pb2.ResolveParticipantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSaga(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/janus.v1.OrchestratorService/GetSaga',
            janus_dot_v1_dot_orchd__pb2.GetSagaRequest.SerializeToString,
            janus_dot_v1_dot_orchd__pb2.GetSagaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeliverEffects(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/janus.v1.OrchestratorService/DeliverEffects',
            janus_dot_v1_dot_orchd__pb2.DeliverEffectsRequest.SerializeToString,
            janus_dot_v1_dot_orchd__pb2.DeliverEffectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchSagas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/janus.v1.OrchestratorService/WatchSagas',
            janus_dot_v1_dot_orchd__pb2.WatchSagasRequest.SerializeToString,
            janus_dot_v1_dot_orchd__pb2.WatchSagasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
