# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: janus/v1/outbox.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'janus/v1/outbox.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from janus.v1 import common_pb2 as janus_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15janus/v1/outbox.proto\x12\x08janus.v1\x1a\x15janus/v1/common.proto\"\xa4\x02\n\nEffectHeld\x12\x1b\n\teffect_id\x18\x01 \x01(\tR\x08\x65\x66\x66\x65\x63tId\x12\x17\n\x07saga_id\x18\x02 \x01(\tR\x06sagaId\x12\x17\n\x07step_id\x18\x03 \x01(\tR\x06stepId\x12\x16\n\x06target\x18\x04 \x01(\tR\x06target\x12\x16\n\x06\x61\x63tion\x18\x05 \x01(\tR\x06\x61\x63tion\x12\x19\n\x08idem_key\x18\x06 \x01(\tR\x07idemKey\x12!\n\x0cpayload_hash\x18\x07 \x01(\x0cR\x0bpayloadHash\x12\x1f\n\x0bpayload_ref\x18\x08 \x01(\tR\npayloadRef\x12\x38\n\x0c\x65\x66\x66\x65\x63t_class\x18\t \x01(\x0e\x32\x15.janus.v1.EffectClassR\x0b\x65\x66\x66\x65\x63tClass\"\x9d\x01\n\x0f\x45\x66\x66\x65\x63tReleasing\x12\x1b\n\teffect_id\x18\x01 \x01(\tR\x08\x65\x66\x66\x65\x63tId\x12\x17\n\x07saga_id\x18\x02 \x01(\tR\x06sagaId\x12\x18\n\x07\x61ttempt\x18\x03 \x01(\rR\x07\x61ttempt\x12\x1f\n\x0b\x63ommit_root\x18\x04 \x01(\x0cR\ncommitRoot\x12\x19\n\x08idem_key\x18\x05 \x01(\tR\x07idemKey\"\xf0\x01\n\x0f\x45\x66\x66\x65\x63tDelivered\x12\x1b\n\teffect_id\x18\x01 \x01(\tR\x08\x65\x66\x66\x65\x63tId\x12\x17\n\x07saga_id\x18\x02 \x01(\tR\x06sagaId\x12\x18\n\x07\x61ttempt\x18\x03 \x01(\rR\x07\x61ttempt\x12+\n\x07outcome\x18\x04 \x01(\x0b\x32\x11.janus.v1.OutcomeR\x07outcome\x12\x1f\n\x0breceipt_ref\x18\x05 \x01(\tR\nreceiptRef\x12!\n\x0creceipt_hash\x18\x06 \x01(\x0cR\x0breceiptHash\x12\x1c\n\tduplicate\x18\x07 \x01(\x08R\tduplicate\"\x9c\x01\n\x11\x45\x66\x66\x65\x63tQuarantined\x12\x1b\n\teffect_id\x18\x01 \x01(\tR\x08\x65\x66\x66\x65\x63tId\x12\x17\n\x07saga_id\x18\x02 \x01(\tR\x06sagaId\x12\x1a\n\x08\x61ttempts\x18\x03 \x01(\rR\x08\x61ttempts\x12\x16\n\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1d\n\nlast_error\x18\x05 \x01(\tR\tlastErrorB7Z5github.com/mustafarslan/janus/gen/go/janus/v1;janusv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'janus.v1.outbox_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/mustafarslan/janus/gen/go/janus/v1;janusv1'
  _globals['_EFFECTHELD']._serialized_start=59
  _globals['_EFFECTHELD']._serialized_end=351
  _globals['_EFFECTRELEASING']._serialized_start=354
  _globals['_EFFECTRELEASING']._serialized_end=511
  _globals['_EFFECTDELIVERED']._serialized_start=514
  _globals['_EFFECTDELIVERED']._serialized_end=754
  _globals['_EFFECTQUARANTINED']._serialized_start=757
  _globals['_EFFECTQUARANTINED']._serialized_end=913
# @@protoc_insertion_point(module_scope)
